FROM python:3.10

ADD weather_api_calls.py /
RUN pip3 install jsonpickle requests flask pika json pymongo bcrypt flask_login

RUN mkdir /app
WORKDIR /app

COPY . /app

EXPOSE 5000

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

CMD ["/app/entrypoint.sh"]