apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: maka4477/backend:v2
        ports:
        - containerPort: 5000  # Port your Flask app is listening on
        # Add other backend configuration here (env vars, volumes, etc.)
